version: '3.2'

services:
  api:
    restart: unless-stopped
    build: .
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-dla.rule=Host(`api.dimonalovesanimals.org`)"
      - "traefik.http.routers.api-dla.entrypoints=websecure"
      - "traefik.http.routers.api-dla.tls.certresolver=myresolver"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.api-dla.middlewares=cors"
